### ISSUE TITLE
Your repo has stolen by this dude [voleggold](https://github.com/voleggold)

### ISSUE THREAD

**Issue by nidin** [manusa/isotope-mail#190]
Here is the stolen repo https://github.com/voleggold/isotope-mail

This dude is stealing repos from other guys and just rewriting history and license 
https://github.com/voleggold/isotope-mail/commit/c72cdad373aa7f49de4b85c0ab98f0fdde9e2147

**Comment by manusa** [comment]
😱 Thanks for reporting.

It looks like a nasty uncool way of forking someone's repo.

Most of the repo stargazaers look suspicious too (or at least they all share the passion for this guy's "projects").

I'll report the user to GitHub staff and see how it goes.

Maybe @voleggold can explain.

**Comment by voleggold** [comment]
I am sorry, I have removed it

**Comment by manusa** [comment]
Thank you
