### ISSUE TITLE
SMTP Attachment

### ISSUE THREAD

**Issue by shift-reality** [manusa/isotope-mail#198]
Currently It's no way to attach files in compose message?

**Comment by manusa** [comment]
Messages can be attached by Drag and Drop. Drag any file to the message editor and your files will be listed at the bottom of the message.

Currently implemented features are listed in this blog post: https://blog.marcnuri.com/isotope-mail-client-introduction/

Feature was implemented in #124

**Comment by manusa** [comment]
![198-file-attachments](https://user-images.githubusercontent.com/488391/53657760-56f18180-3c57-11e9-95c3-f03c6fdd4204.gif)
