### ISSUE TITLE
FE: Autocomplete email addresses

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#199]
## Description

E-mail and names for e-mail recipients in Message Editor are autocompleted when user starts typing in any of the recipient fields.

Addresses provided in autocomplete to be fetched from messages.cache in Redux store.

## Requirements
- [x] Autocompletion is available for all types of recipients in MessageEditor (To, Cc, Bcc)
- [x] Suggested addresses appear in a popup list
- [x]  List is traversable using arrow keys
- [x] Elements can be selected pressing Enter key
- [x] List is hidden pressing Escape key, input is cleared pressing Escape key again
- [x] List shows at most 10 suggestions
- Suggestions are filtered by words typed by the user
  - [x] E-mail addresses are filtered using input typed by the user ignoring case
  - [x] Input is tokenized into words
  - [x] E-mail addresses must contain all words typed by the user in **any** order
- [x] Suggestions are sorted by frequency in descending order (most frequent e-mail addresses in the cache appear first)

**Comment by shift-reality** [comment]
Good idea!!
--
"user starts typing" and one click event too please... Just click on empty prompts should open dropdown.
I suggest: Dropdown list should be sorted by "number of mails which i sent to this  recipient " (NOT how much i received from). If possible?
--
But maybe use some contacts storage in backend? Like Mysql/pgsql..
 If user goes to new browser then names should persist...

**Comment by shift-reality** [comment]
I found another option in other email-client is available to store address book in IMAP server: need create 1 hidden letter with MIME on IMAP server and keep contacts list as CSV in body, so backend don't needed to use any external storage, this hidden mail updated using (imap_mail_compose) function...
This possible to implement contact syncing between many browsers in that way?

**Comment by shift-reality** [comment]
![screenshot from 2019-03-04 21-40-04](https://user-images.githubusercontent.com/29734946/53758219-1c415080-3ec6-11e9-91ac-d1ad40bac392.png)

**Comment by manusa** [comment]
> Good idea!!
> 
> "user starts typing" and one click event too please... Just click on empty prompts should open dropdown.
> I suggest: Dropdown list should be sorted by "number of mails which i sent to this recipient " (NOT how much i received from). If possible?
> 
> But maybe use some contacts storage in backend? Like Mysql/pgsql..
> If user goes to new browser then names should persist...

I like your idea of displaying the drop-down when user clicks on the empty prompt or maybe pressing the down arrow.
Current implementation using [react-autosuggest](https://github.com/moroshko/react-autosuggest) doesn't provide an easy way to show suggestions based on events.
Suggestions are shown based on the value of the prompt, so either they are always shown or they follow a rule such as `value.trim().length > 0`.
I don't like having the drop-down always open as it blocks user interaction, so for now displaying the drop down requires the user to always type something (as a workaround you can always type `@` to display **all** the cached addresses).

E-mails **are** sorted by frequency. User's e-mail address **is** included in this list. One of the main challenges of the application is to _know_ what is the logged user's e-mail address. There is no easy way (or at least that I know of) to do so with regular IMAP protocol, so filtering this address from the list is challenging.

The whole point of the application design is not to create a dependency with a database (at least for core functionality).
There are plans to persist settings and an address book in future versions. For this purpose I'm thinking of 2 different approaches:
 - Do something like you suggest in your [other comment](https://github.com/manusa/isotope-mail/issues/199#issuecomment-469370140): Settings/address book is persisted using a JSON in a fake e-mail message in a `.isotope` folder in the user's IMAP mailbox.
- Create a specific microservice, with database persistence to store any data that has to be shared across user browsers/sessions.

Anyway, these are just plans for future releases, for the scope of the current ticket we are considering only gathered/cached e-mail addresses.

**Comment by manusa** [comment]
![199-address-autocomplete](https://user-images.githubusercontent.com/488391/53784588-0d828a00-3f16-11e9-9b4f-cecbc61cd72b.gif)
