### ISSUE TITLE
Duplicates in field "To"

### ISSUE THREAD

**Issue by shift-reality** [manusa/isotope-mail#201]
Hi
I have noticed for receivers list like "external-not-reachable@isotope isotope@isotope isotope@isotope isotope@isotope" in some email...
Can you add rule "unique" to email list in "To" field?
Or some filter to remove duplicates...
Thanks

**Comment by manusa** [comment]
What you've noticed is just a test e-mail to pre-fill autocomplete options for QA purposes of ticket #199.

Duplicate e-mail addresses is something normal and expected in any mail client, following are screen-shots of 2 of the most popular clients with duplicate e-mail addresses:

![image](https://user-images.githubusercontent.com/488391/53752400-d1680e80-3eae-11e9-8648-6d3ce4f3589d.png)

![image](https://user-images.githubusercontent.com/488391/53752554-2c016a80-3eaf-11e9-9f2e-474c59ae17e9.png)


Yes, future developments may include an alert in case an e-mail address is duplicate, or filtering of repeated addresses in reply-all action.

**Comment by shift-reality** [comment]
ok
