### ISSUE TITLE
FE: Add quick filters to message list

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#210]
## Requirements
- [x] Messages in message list view can be filtered according to a set of _quick_ filters:
  - [x] All: No filters applied
  - [x] Read: List only read messages
  - [x] Unread: List only unread messages
  - [x] Flagged: List only flagged messages
- [x] Filter button to be displayed in TopBar
- [x] Filter button to display a popup with options when clicked
- [x] Popup to contain all available filter options
- [x] Selected option must appear highlighted and marked with an _active_ check 
- [x] Filter button highlighted when any option except _All_ is selected
- [x] Selected option / filters are cleared whenever a folder is selected (even if it's the same folder)

**Comment by shift-reality** [comment]
Bug: flagged messages don't show from nested folders, only one level

**Comment by shift-reality** [comment]
Also useful filter is "Show mails with attachments" "Show mails without attachments"

**Comment by manusa** [comment]
> Bug: flagged messages don't show from nested folders, only one level

Not a bug, **expected** behavior.

Quick filters apply on the current view, so only messages from the selected folder (_current level_) and that **have** been loaded into the Redux store will be filtered (If the current folder has 8000 messages but only 3000 have been loaded, filter will only apply to the loaded 3000 messages. While messages are still loading, filter will be reapplied for each batch that is persisted in the Redux store).

> Also useful filter is "Show mails with attachments" "Show mails without attachments"

This is a good suggestion and was also considered but has not been implemented due to the limitations of the current design. "Envelope" information right now doesn't include if the message has attachments or not. Once this information is included this functionality will be added as a new feature for the Message list view quick filters.

**Comment by shift-reality** [comment]
Is hard to implement extra pseudo-folder named "Flagged messages"? and then
-when opened load all flagged messages  from IMAP server to redux?
Or flag stored only locally, not in IMAP?

**Comment by shift-reality** [comment]
Or just make two functions: flag and important
And show all important messages in dedicated folder
?

**Comment by manusa** [comment]
> Is hard to implement extra pseudo-folder named "Flagged messages"? and then
> -when opened load all flagged messages from IMAP server to redux?
> Or flag stored only locally, not in IMAP?

> Or just make two functions: flag and important
> And show all important messages in dedicated folder
> ?

Message flags are part of the IMAP [specification](https://tools.ietf.org/html/rfc3501#section-2.3.2).
Not all IMAP servers support additional flags besides from system flags.

The scope of this issue is to cover message list quick filtering in order for the user to be able to quickly find messages the rest is out of scope.

Future plans include an interface for IMAP search which hopefully will achieve some of the things you are suggesting (such as listing all flagged messages in all folders)

**Comment by manusa** [comment]
![210-message-list-quick-filters](https://user-images.githubusercontent.com/488391/54711173-9cfc7f80-4b49-11e9-8974-fd200682dbba.gif)
