### ISSUE TITLE
Trash folder can  be cleared with a single action ('Empty folder' button)

### ISSUE THREAD

**Issue by shift-reality** [manusa/isotope-mail#219]
## Requirements
- Trash folder can be cleared with a single action
- [x] Button to empty folder must be visible **only** when trash folder is selected
- [x] Pressing the button will show a confirm dialog
  - [x] User can cancel action by pressing 'Cancel' in confirm dialog, dialog closes without further changes
  - [x] User can confirm action by pressing 'Ok'
  - [x] If action is confirmed, all messages from folder will be removed even if they haven't been loaded in the FE Redux store

**Comment by manusa** [comment]
![219-trash-clear-button](https://user-images.githubusercontent.com/488391/55574271-4b88ee80-570c-11e9-9b0a-360b5ce15c0a.gif)
