### ISSUE TITLE
Close Compose view if folder clicked

### ISSUE THREAD

**Issue by shift-reality** [manusa/isotope-mail#233]
3 options:
-hide folders & topbar if compose;
-disallow change current folder;
-Leave Confirm dialog / Save Draft dialog;

GIF:
![Peek 2019-03-20 11-05](https://user-images.githubusercontent.com/29734946/54672284-6a7a6480-4b00-11e9-9b1e-c63aa79cdca1.gif)

**Comment by manusa** [comment]
Issue is not applicable after #304 implementation.
Message Compose is modal.
