### ISSUE TITLE
bug:Save draft content to local storage

### ISSUE THREAD

**Issue by shift-reality** [manusa/isotope-mail#235]
Reloading tab When compose view is open causes content lost. But view is still open
Need save content of editor, subject and receivers list
 to local storage or implement Drafts feature

**Comment by shift-reality** [comment]
(firefox 60.5.1esr bug only): Don't remember editor content

**Comment by shift-reality** [comment]
proof of issue in FF
![Peek 2019-03-20 11-20](https://user-images.githubusercontent.com/29734946/54673102-3dc74c80-4b02-11e9-9d9a-fca541a57df7.gif)

**Comment by shift-reality** [comment]
Google chrome
![chr](https://user-images.githubusercontent.com/29734946/54674849-ed51ee00-4b05-11e9-8508-9ec65ef67d51.gif)

**Comment by manusa** [comment]
Fixed in scope of #263
