### ISSUE TITLE
FE: Add tooltips to Top-Bar action buttons

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#239]
## Requirements

- Top-Bar buttons must contain tooltip with a hint indicating their action.
- Affected icons:
  - [x] Collapse SideBar
  - [x] Show SideBar
  - [x] Mark read
  - [x] Mark unread
  - [x] Delete
  - [x] Quick Filters
  - [x] Return to list
  - [x] Reply all
  - [x] Forward

## Created by

- #214

**Comment by manusa** [comment]
> Hi Marc,
> 
> Your BrowserStack account registered to ****@****.** is now active for testing, till 27th Mar, 2020.
> 
> Your sponsored plan details are:
> Automate Mobile x 5 Parallel Tests (Up to 5 Users) [New]
> 
> If you need any help getting started or inviting your team members to BrowserStack, reply to this email and we will be in touch.
> 
> Happy Testing!
> The BrowserStack Team
> www.browserstack.com

**Comment by manusa** [comment]
> Hi Marc,
> 
> Welcome to BrowserStack's Open Source community!
> 
> I have activated your sponsored subscription for 1 year. You now have full access to our paid products and benefits. On 27th of March, 2020, we will review and renew your subscription.
> 
> Happy testing!
> Regards,

**Comment by shift-reality** [comment]
add labels in compose view to please
There button looks like Trash bin (delete draft & back to mail-list button)

**Comment by shift-reality** [comment]
in right bottom corner

**Comment by manusa** [comment]
Hints should be available in **all** TopBar elements, QA is not completed yet, but you should be able to see them.

**Comment by manusa** [comment]
![#239-top-bar-tooltips](https://user-images.githubusercontent.com/488391/55212561-7c3ec480-51f0-11e9-8a86-24359b9f49b2.gif)
