### ISSUE TITLE
BUG: Message move/mark as read breaks folders

### ISSUE THREAD

**Issue by manusa** [manusa/isotope-mail#292]
## Description
- When messages are moved, folder names are broken
![image](https://user-images.githubusercontent.com/488391/58148817-874a2a00-7c60-11e9-83df-4ac0a361af03.png)
- To reproduce, move messages from a parent folder to one of its immediate children

## Requirements
- Updating of folder metadata should be performed using a separate action just to modify its properties.

**Comment by Dinamots** [comment]
I send a message to myself and opened the mail that i received broked folders too

**Comment by manusa** [comment]
Hi @Dinamots,
Please provide steps to reproduce or some kind of video or image sequence showing the error.

**Comment by Dinamots** [comment]
[test.zip](https://github.com/manusa/isotope-mail/files/3207805/test.zip)

**Comment by manusa** [comment]
Hi @Dinamots 

I guess your problem is this one:
![image](https://user-images.githubusercontent.com/488391/58194806-cdd26f80-7cc6-11e9-8d1e-eae45860af96.png)

Is this normal (having an INBOX within an INBOX)?
![image](https://user-images.githubusercontent.com/488391/58194846-e2166c80-7cc6-11e9-9b3d-950f78a4a033.png)

What IMAP server are you using?

**Comment by Dinamots** [comment]
I'm using ssl0.ovh.net imap server

**Comment by manusa** [comment]
Folder issue should now be fixed.
Regarding the multiple folders being marked as INBOX, #294 has been opened.

OVH seems to be using Dovecot:
![image](https://user-images.githubusercontent.com/488391/58347589-88e14100-7e5e-11e9-94e7-3b156939cefe.png)
![image](https://user-images.githubusercontent.com/488391/58347606-94cd0300-7e5e-11e9-96f5-462dd37d0178.png)

**Comment by manusa** [comment]
![292-child-folders-updated-OK](https://user-images.githubusercontent.com/488391/58365252-af849380-7ec1-11e9-9a4c-c83f521fbd0f.gif)
