### ISSUE TITLE
How to change port 80 in Docker config?

### ISSUE THREAD

**Issue by habibshahid** [manusa/isotope-mail#347]
Hello,

Great project. Could you please help me out and advise on how to change port 80 in the docker configs? or is it at all possible?

Thanks

**Comment by manusa** [comment]
Hi,
Sorry, I didn't see your issue earlier.

>...or is it at all possible?

Yes, of course, you can change the ports given that you run your application in some sort of containerized environment.

To change your ports using the docker-compose example you should modify the [following line](https://github.com/manusa/isotope-mail/blob/42220b771e36d7e969ae52ec4cdcc618d30972a5/deployment-examples/docker-compose.yml#L8).

There are many options to deploy the application and we recommend having an API gateway to act as a reverse proxy. So changing the port really depends on how you are planning to deploy it.
